### ISSUE TITLE
Document the state of Elasticluster support for Microsoft Azure

### ISSUE THREAD

**Issue by zfrenchee** [gc3-uzh-ch/elasticluster#303]
Hello! 

We're interested in using this project to build ourselves a cluster for Azure. Some time ago, Windows Azure became Microsoft Azure when it began supporting linux VMs. We'd like to use linux VMs from Azure with Slurm, and I can't find much documentation as to what the status of Azure support is -- it's hardly mentioned anywhere. All I found was this excellent [blog post](http://c-square.github.io/2015-11-19-create-a-cluster-on-windows-azure/), but unfortunately it's for windows VMs -- it was published before the transition to "Microsoft Azure". 

Updating the documentation would be tremendously helpful! I looked through `/providers/` but couldn't find any mention of Azure there either...

**Comment by zfrenchee** [comment]
It seems like there exists [a fork that may have been built with azure in mind](https://github.com/bobd00/elasticluster/blob/master/azure-sample-config). Have the two totally diverged? Will they ever be merged?

**Comment by dsteinkraus** [comment]
Hello, that Azure fork is my work and I submitted a [pull request](https://github.com/gc3-uzh-ch/elasticluster/pull/168) back in June 2015. After an initial positive response, the PR went dormant and I had to move on to other projects. I'm willing to invest some time if I can help move this forward - it worked quite well at the time, but a lot has probably changed in a year.

**Comment by zfrenchee** [comment]
@dsteinkraus this looks like great work! I'm sorry to hear it was never merged. 
1. Did you build this PR with Azure's Linux offering in mind? 
2. What do you think is needed to go from here to merge-able?

**Comment by dsteinkraus** [comment]
Thank you. Yes, Linux was the primary target (I was asked to build this to support some bioinformatics work using gridengine).

To the best of my knowledge it was fully ready to merge in June of last year. There were no conflicts then. I haven't kept up on changes since. I know Azure has moved to a new configuration model, and I don't know whether the old model still works, or is deprecated. And changes to elasticluster and Ansible might have broken something. I'll try it out and see how things look.

**Comment by zfrenchee** [comment]
Great! Thanks @dsteinkraus! Let me know how it goes and whether I can help at all (I'm very new to these technologies but happy to take a look at anything)

**Comment by riccardomurri** [comment]
Hello @dsteinkraus  and @zfrenchee !

Thanks for your availability on working towards Azure support!  I absolutely want to merge PR #168 (and its cousin #167) during the 1.4 release cycle, i.e., likely in November.  I worked mostly on the playbooks since I took over maintenance of ElastiCluster so I do not expect large code conflicts when merging.  I have no idea about the state of the Azure API or configuration mechanism, since we do not use Azure here -- so any help from you experts is very much appreciated!

P.S. Perhaps the [ElastiCluster mailing-list](https://groups.google.com/forum/#!forum/elasticluster) is a better venue for this discussion?

**Comment by dsteinkraus** [comment]
Hello @riccardomurri ! I'm glad to know that there is interest in merging this. I'll do some initial testing and start a thread on the mailing list with my findings so we can continue the discussion. I'm pretty busy right now so a November timeframe sounds good (sooner if possible, of course).

**Comment by zfrenchee** [comment]
@riccardomurri and @dsteinkraus 
A November timeline is much too long for me, sadly, but if you do some testing @dsteinkraus and figure out what, if anything, needs fixing, I can take a look and maybe we can finish this sooner.

**Comment by zfrenchee** [comment]
@dsteinkraus Any progress on this?

**Comment by dsteinkraus** [comment]
Actually I’m looking at it right now.

On a clean Ubuntu 14.04 LTS instance, I was able to get the bobd00/elasticluster fork to install, but it won’t run, due to incompatibilities with the current Azure SDK.

In June of last year, I was running against version 0.11.0 of the Azure SDK for Python. The current version is 2.0.0rc5. Based on a first look at the release log (https://github.com/Azure/azure-sdk-for-python/releases) there have probably been a number of breaking changes. I’ll have to start going through step by step and see what they are.

The better news: it appears (https://github.com/Azure/azure-sdk-for-python/tree/master/azure-servicemanagement-legacy) that the “legacy” API for managing Azure resources (which I used) is still available, at least for now. This improves the odds of getting my provider code working again relatively quickly. The new “ARM” API (Azure Resource Manager) would likely be a significant rewrite.

I’ll continue working on it as time permits.
