### ISSUE TITLE
GridEngine cannot be installed on CentOS7

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#350]
Running the GridEngine playbooks on RHEL/CentOS7 stops with the following error::

    TASK [Install GridEngine RPM packages] *****************************************
    failed: [master001] (item=[u'gridengine-qmaster', u'gridengine-execd', u'gridengine-qmon']) => {"changed": false, "failed": true, "item": ["gridengine-qmaster", "gridengine-execd", "gridengine-qmon"], "msg": "No Package matching 'gridengine-qmaster' found available, installed or updated", "rc": 0, "results": []}

It looks like the GridEngine packages were removed from EPEL;
a [COPR repository][1] curated by Dave Love (maintainer of "Son of
Grid Engine") hosts the SoGE packages, but they install in a different
location (`/opt/sge`) so some adaptation work is needed to make them
run.

[1]: https://copr.fedorainfracloud.org/coprs/loveshack/SGE/

**Comment by nicoulaj** [comment]
FYI, I got a working version with SGE on CentOS 7 on my linked branch.

This is quick and dirty because I need it working right now, there are several issues:
 * I inverted the SGE setup/NFS setup order due to #347, so Debian support is probably broken
 * The RPMs for RHEL do not contain systemd init files, so there are some workarounds to start `sge_execd` manually
 * I used `set_fact` to set global variables for `SGE_ROOT`, maybe there is a cleaner way ? I never Ansible until now, I don't know the good practices...

**Comment by riccardomurri** [comment]
Is this still current?  I'd guess it were fixed by merging #366, is it not?

**Comment by nicoulaj** [comment]
Sorry, I could not test the latest changes, but I guess this one can be closed if it is covered by #366

**Comment by riccardomurri** [comment]
Well, it should but I'd like some independent confirmation :-)

**Comment by nicoulaj** [comment]
@riccardomurri I just tested it on master 3e83f55, everything looks like fine on my side.

**Comment by riccardomurri** [comment]
Thanks @nicoulaj I'm closing the issue then.
