### ISSUE TITLE
Hadoop playbook fixed on JDK 7 requirement

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#379]
share/playbooks/roles/hadoop-common/tasks/main.yml

starting from ubuntu 16.04, the minimal available openjdk package seems to be version 8

the playbook should introduce a check on the current ubuntu version and distinguish between pre 16.04 (ok to ask for openjdk-7-jre-headless) and post 16.04 (ask for openjdk-8-jre-headless)

S.

**Comment by riccardomurri** [comment]
Well, there's two questions here:

* if the Java version does not matter, then we can just install `default-jdk` (would be JDK 8 on Ubuntu 16+ and JDK 7 on previous versions)
* if the Java version *does* instead matter, but we only need JRE instead of JDK, then the JRE 7 *is* available on Ubuntu 16.04 as `openjdk-7-jre`

**Comment by riccardomurri** [comment]
Took the route of installing `default-jre-headless`.
