### ISSUE TITLE
Don't run playbooks as root by default

### ISSUE THREAD

**Issue by HackerMD** [gc3-uzh-ch/elasticluster#389]
The *elasticluster* playbooks currently need to be run as root.

This can cause problems when combined with other non-*elasticluster* playbooks, tasks or roles and  when used for containers, see [Ansible docs](http://docs.ansible.com/ansible-container/roles/writing.html#make-images-that-don-t-require-root).

**Comment by riccardomurri** [comment]
I do not see much of a problem in combining user-privilege and root-privilege
playbooks in a top-level playbook (provided you use Ansible >= 2.0 so that
`include: ... become: yes` works). 

For example, let's run a simple playbook that creates one file, once with
user-level privilege and once with root-level privilege::

    $ /tmp cat touch.yml 
    ---

    - name: Create file
      file:
        dest='{{filename}}'
        state=touch

    $ /tmp cat test.yml 
    - name: Test root playbook inclusion

      hosts: all

      tasks:

        - include: touch.yml filename='/tmp/user.yml'

        - include: touch.yml filename='/tmp/root.yml'
          become: yes

The playbook runs and includes correctly::

    $ /tmp ansible-playbook -c local -i localhost, test.yml

    PLAY [Test root playbook inclusion] ********************************************

    TASK [setup] *******************************************************************
    ok: [localhost]

    TASK [Create file] *************************************************************
    changed: [localhost]

    TASK [Create file] *************************************************************
    changed: [localhost]

    PLAY RECAP *********************************************************************
    localhost                  : ok=3    changed=2    unreachable=0    failed=0

Here's the result::

    $ /tmp ls user.yml root.yml -l 
    -rw-r--r-- 1 root   root   0 feb  6 12:09 root.yml
    -rw-rw-r-- 1 rmurri rmurri 0 feb  6 12:09 user.yml
