### ISSUE TITLE
Pause GCE cluster instead of destroying it on "stop"

### ISSUE THREAD

**Issue by jmrk84** [gc3-uzh-ch/elasticluster#583]
A nice feature would be the ability to properly pause a GCE (+maybe other backends) cluster. "elasticluster stop x" currently destroys the instances + disks, which means that significant setup time is required even for small-sized clusters (100+ compute nodes). Since disk space is relatively cheap in comparison to compute time, it should be sufficient in many cases to stop the instances instead of destroying them. This can be done manually already, but seems to lead to some minor(?) issues, such as that the original IPs, which change upon stop/start are incorrect. Related to issue https://github.com/gc3-uzh-ch/elasticluster/issues/505.

**Comment by manuelesimi** [comment]
`pause/resume`

**Comment by ndmckinley** [comment]
I've been working on this - I've got clusters pausing and resuming, no problem, but there's a problem.  Most of the ansible playbooks do not create clusters that will survive a reboot.  That is, they connect masters and workers by IP address (which usually changes between reboots), or they don't set their respective services to come up on a reboot.

This isn't super surprising - nobody writing those playbooks would have expected the use case where the IP changes out from under you - but it does make this feature a bit less useful.

I've got three ideas to fix this, in rough order of my preference:
- Require an `elasticluster setup` call after the `elasticluster resume` call (or fold it in to the `resume`) - essentially rerun the provisioner.  It's usually faster the second time through, of course - similar to running setup after `start` - but it's not instantaneous, especially for larger clusters.
- Give master node(s) a fixed IP address at start, which costs more money on some clouds, but which should solve problems at least for slurm (remaining tools to be tested).
- Create new "restart-config" playbooks which will get machines ready after a reboot (should just be config deploys and service restarts)  This is more time-consuming for me, and since slurm is the only tool I know well enough to write those for, the feature might be initially released with only slurm support.

Does anyone have an opinion on which approach they'd like best?  They all have their pros and cons.

**Comment by riccardomurri** [comment]
> Most of the ansible playbooks do not create clusters that will survive a reboot. That is, they connect masters and workers by IP address (which usually changes between reboots)

Are IP addresses expected to change on GCP after a VM reboot?  My only experience with long-running clusters is with OpenStack, where IP address stay allocated to a VM until it is destroyed.

> I've got three ideas to fix this, in rough order of my preference:
>
> * Require an elasticluster setup call after the elasticluster resume call (or fold it in to the resume) - essentially rerun the provisioner. It's usually faster the second time through, of course - similar to running setup after start - but it's not instantaneous, especially for larger clusters.

I think this is the quicker one to implement; running the entire playbook will be *slow*, but a lighter-weight variant that should be enough for most cluster types is discussed in the followup to your option 3.

> * Give master node(s) a fixed IP address at start, which costs more money on some clouds, but which should solve problems at least for slurm (remaining tools to be tested).

I don't think this will solve the problem: every node needs to know the address of each other, so either they are all given fixed IP addresses, or they all need to contact the master to get the new address -- which would basically be a variant of your option 3. below.

> * Create new "restart-config" playbooks which will get machines ready after a reboot (should just be config deploys and service restarts) This is more time-consuming for me, and since slurm is the only tool I know well enough to write those for, the feature might be initially released with only slurm support.

I don't think it would be doable to have a "restart-config" script for each and every cluster type.  However, I cannot think of a service that requires membership by *IP addresses* instead of host names (well, maybe CephFS -- need to check).  So we can quite probably reduce the problem to rebuilding `/etc/hosts` at boot time, which doesn't look that bad.  A few possibilities off the top of my head:

* Just have `elasticluster` push the new `/etc/hosts` to all VMs via Ansible or plain `scp`/`sftp` upon cluster resume.  This is basically a ligher-weight variant of your option 1.

* Use NIS to distribute the hosts map, instead of relying on `/etc/hosts` (i.e., have `hosts: files nis dns` in `/etc/nsswitch.conf`.  The NIS master server can be found by broadcast so we do not need to know its IP address in advance.  However, do I remember correctly that IP broadcast does not work on GCP? (since each VM is its own /32 network)

* In a similar vein, we could instead use SLP or Avahi/Rendezvous or mDNS to locate all members of the cluster -- these require multicasting (instead of broadcasting) so might run into the same issues as the NIS solution: how many cloud infrastructures support IP multicasting? (and if they do, NIS is easier because ElastiCluster already installs it)

We need to check if all cluster types can handle membership by host name only and how well they can cope with changing IP addresses.  But I guess this is something we will only find out once we implement something and release it...

**Comment by ndmckinley** [comment]
>Are IP addresses expected to change on GCP after a VM reboot? My only experience with long-running clusters is with OpenStack, where IP address stay allocated to a VM until it is destroyed.

Yes, and on AWS.  Those are the only two providers I'm familiar with personally - I didn't know that OpenStack left IP addresses the same, that's a nice touch.

> However, do I remember correctly that IP broadcast does not work on GCP? (since each VM is its own /32 network)

GCP's networking is nuanced, but there are networking configurations you can use that support broadcast.  Quick summary: you can broadcast within a subnetwork, but not across subnetworks.

I like the idea of pushing `/etc/hosts` up on restart - that's clearly a good idea and I'll try to implement that.

Thanks!

**Comment by ndmckinley** [comment]
Ah, there's an issue.  It's not that hard to push the `/etc/hosts` file up - but that doesn't fix the issue.  `slurmctld` still won't start up on its own.  Looks to me like some environment variables that need to be set are not present.  I imagine (but haven't checked yet) that some of the other cluster types have got the same issue - it seems likely that they'd set environment variables that reset on restart, or neglect to set up `/etc/init.d` scripts correctly, since it has never been important before right now.  That's just good engineering, the YAGNI principle.  :)

I'll figure it out!  But that's the delay, right now.

**Comment by ndmckinley** [comment]
Cool, yeah, it's an easy one - on a GCE cluster the hostname of the machine gets reset every time the instance reboots, so you have to set the hostname then restart the services, and slurm's default elasticluster configuration happens to demand that the instance's hostname match a value in a config file.

Again, easy fix, and I'm on it, but it's an issue that's specific to this provider/cluster type pair, which makes me a little concerned there may be issues like this hiding in other provider/cluster type pairings.

**Comment by riccardomurri** [comment]
A side note:

> on a GCE cluster the hostname of the machine gets reset every time the instance reboots

This has come up already in different issues (e.g., see: https://github.com/gc3-uzh-ch/elasticluster/issues/582#issuecomment-423302561 ) -- if you have a better general solution, I'd be very keen to implementing it.

**Comment by riccardomurri** [comment]
> slurm's default elasticluster configuration happens to demand that the instance's hostname match a value in a config file

Yeah, there might be a couple of issues lurking ahead of us here:

1. the current `slurm.conf` template (`elasticluster/share/playbooks/roles/slurm-common/templates/slurm.conf.j2`) uses `ControlAddr=...` to refer to the SLURM controller daemon host by IP address.  I think we can just use the host name instead, and SLURM will use `getaddrinfo()` to resolve it.

2. Which brings up the second issue: the correct host name / IP address pair must already be in `/etc/hosts` when SLURM is started.  However, the init system cannot tell when this is going to happen, since the correct `/etc/hosts` is pushed from the ElastiCluster control machine.  So I guess the only solution is to let `init` try to start SLURM normally and then ElastiCluster should check and possibly restart it when `/etc/hosts` has been pushed.

3. So now we need not just to push `/etc/hosts` but also check for services and restart them possibly... I think the easier way to do it would be to have ElastiCluster's `resume` command run an additional playbook (e.g., stored in `elasticluster/share/playbooks/resume.yml` -- as opposed to `main.yml` which gets run on `elasticluster setup`) which rewrites `/etc/hosts` and then restarts services as needed.  (I can volunteer to write this playbook if you're not comfortanle with Ansible.)  I think doing so would allow us to re-use most of the code that is already set up for start/setup with minimal changes (basically, just make the main playbook name a parameter).

What do you think?

**Comment by riccardomurri** [comment]
I have removed the `ControlAddr=...` line from `slurm.conf` in commit 04a2928; this should make the SLURM config in ElastiCluster completely independent of IP addresses.

**Comment by jmrk84** [comment]
FYI, the IP changes were not an issue for SGE on GCE, things just kept working (I suspect because the internal IPs of GCE were used which did not change, just the external IPs change).

**Comment by ndmckinley** [comment]
> A side note:
> 
> > on a GCE cluster the hostname of the machine gets reset every time the instance reboots
> 
> This has come up already in different issues (e.g., see: [#582 (comment)](https://github.com/gc3-uzh-ch/elasticluster/issues/582#issuecomment-423302561) ) -- if you have a better general solution, I'd be very keen to implementing it.

I do, actually!  I can make it so that the machine resets its own hostname on restart.  That feels like a separate PR, but I can do it next.  :)

> 3. So now we need not just to push `/etc/hosts` but also check for services and restart them possibly... I think the easier way to do it would be to have ElastiCluster's `resume` command run an additional playbook (e.g., stored in `elasticluster/share/playbooks/resume.yml` -- as opposed to `main.yml` which gets run on `elasticluster setup`) which rewrites `/etc/hosts` and then restarts services as needed.  (I can volunteer to write this playbook if you're not comfortanle with Ansible.)  I think doing so would allow us to re-use most of the code that is already set up for start/setup with minimal changes (basically, just make the main playbook name a parameter).
> 
> What do you think?

This feels right to me; it's the path I'm headed down.  I may not have time to get to it today, but I am comfortable with Ansible in general (I contribute to the GCP Ansible provider from time to time).  If you beat me to it, heck, that rocks.  :)  A work-in-progress version of what I've got so far is sitting at https://github.com/ndmckinley/elasticluster/tree/pause-instances - there's still concurrency left to do, as well as this restart issue, but I'm getting there.

**Comment by ndmckinley** [comment]
Great, I've gotten slurm working after a resume!  It's way, way, way faster.  I'll still have to throw parallelism in there for the pauses and the actual resume calls, but that should be pretty easy.  Still WIP at https://github.com/ndmckinley/elasticluster/tree/pause-instances.

**Comment by riccardomurri** [comment]
Excellent!  Thank you very much! :-) I hope to have a look at the code on Thursday (still one more deadline to go...)

**Comment by ndmckinley** [comment]
Parallelism is done!  I'll start checking the other cluster types to see if they also need work done after a resume.

**Comment by ndmckinley** [comment]
Got a couple of them working - wanted to get it out there for examination and initial review.

**Comment by jmrk84** [comment]
Fantastic news, I am currently testing your branch @ndmckinley Pause and resume seems to work more or less in GCE, apart from the following on resume:

TASK [Ensure changes to hostname are not overwritten by cloud-init] *****************************************************************************************************************
fatal: [compute001]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '__colon__' is undefined\n\nThe error appears to have been in '/home/joergen_kornfeld/bin/elasticluster/src/elasticluster/share/playbooks/roles/common/tasks/hostname.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure changes to hostname are not overwritten by cloud-init\n  ^ here\n"}

I also had to hack gce.py and change the IP to the internal IP (since I cannot have ssh to the external IP on a Google owned project):

                        #ip_public = interfaces[0]['accessConfigs'][0]['networkIP']
                        ip_public = interfaces[0]['networkIP']

Could that change have caused the hostname issue?

@riccardomurri is there any particular reason why the external IP is currently being used? The advantage of the internal IP would be that it doesn't change. Additionally, there might be GCE charges on traffic running over the external IPs (not sure whether that is true when they are in the same VPC though).

**Comment by riccardomurri** [comment]
@jmrk84 Regarding this error:

> The task includes an option with an undefined variable. The error was: 'colon' is undefined

It should be fixed in https://github.com/riccardomurri/elasticluster/tree/pause-instances -- a PR for @ndmckinley is underway...

**Comment by ndmckinley** [comment]
Aha, thanks for the catch!  I'll grab that commit, and make the changes requested in that code review.  Thanks, folks!  :)

**Comment by riccardomurri** [comment]
Regarding this instead:

> is there any particular reason why the external IP is currently being used?

Not all clouds support them or do allocate multiple IP addresses automatically.  

I guess we can try to expose ElastiCluster's idea of "preferred/connection IP" as the "public IP" and then assume other IP addresses (if any) should be used for intra-cluster communication...  (But what should ElastiCluster do if there are more than 1 "internal" IP addresses?)

Anyway, I think this effort belongs in a different issue :-) merging pause/restart should not wait until the public/private IP support is implemented...

**Comment by jmrk84** [comment]
I've tested pause/resume with a 1000 core slurm cluster on GCE and the speed-up is really amazing. Initial setup takes over 30 minutes (with around 30 compute nodes and this gets slower with more), resume about a minute or so. @ndmckinley @riccardomurri Thank you very much!

**Comment by ndmckinley** [comment]
While I was testing the last handful of changes here, I found an issue with launching SLURM on GCE - something to do with the iptables files under netfilter-persistent.  I don't see any recent changes there, but I'm looking into it.

**Comment by jmrk84** [comment]
I encountered this as well, but only on Debian9, not Ubuntu 16 LTS.

**Comment by ndmckinley** [comment]
Same.  I want to fix it, though!  It's definitely not ideal that it worked last week and doesn't work now.

**Comment by ndmckinley** [comment]
I'm switching to ubuntu LTS to test my last handful of changes, but I'll file a new issue with what I've learned about the debian stretch issue.

**Comment by riccardomurri** [comment]
The issue with `netfilter-persistent.service` has been independently reported as #609 (also on Debian 9)
