### ISSUE TITLE
Support spot instances

### ISSUE THREAD

**Issue by yarikoptic** [gc3-uzh-ch/elasticluster#60]
It seems to me on a brief look that elasticluster doesn't have (yet) support for reserving Amazon spot instances.  It would be nice if those were "supported"

**Comment by pgm** [comment]
Months have gone by, so it's probably clear that I never got spot instances working.  In any case, just posting an update here in case someone stumbles across this issue and wonders what happened. 

I still think it should be an easy thing to add, however, I struggled with simply getting elasticluster to reliably set up the nodes.  (I started right after ansible versions switched and I think some other recent changes at the time caused me problems.  I suspect elasticluster may have stabilized since then.)   Stumbling over those issues and a shortage of time, I never finished it, and have been using the datacratic branch of starcluster again instead.

**Comment by xanderdunn** [comment]
Also require spot instance support here.

**Comment by riccardomurri** [comment]
Let's try to target this in 1.4.

**Comment by rubenvereecken** [comment]
A few interested parties here for spot instances. Absolute must, stuck with starcluster now for exactly that reason.

**Comment by elipapa** [comment]
spot instances and autoscaling / load balancing would be great for me too. a showstopper at the moment.
ansible has core modules to deal with autoscaling configuration...

**Comment by wvangeit** [comment]
+1

**Comment by machbio** [comment]
Spot Instances will definitely help me Migrate from Starcluster to ElasticCluster...If you could start off with the design document for how you would like to Implement - we might be able to contribute with PR..

**Comment by riccardomurri** [comment]
Hello - sorry for the delay in answering to this popular thread!

I do not plan to work on spot instances soon (we do not have a local use case for them, and I must give priority to other stuff) but I'm certainly very open to merging a PR that adds support for them.

The equivalent support on the Google Cloud has been already added in commit https://github.com/gc3-uzh-ch/elasticluster/commit/848b8a8e9fb375528f16fb654b9daaa5a9caae14 -- any similar solution for AWS would be very welcome.  

For instance, just adding a parameter `allow_spot_instances=yes/no` to the AWS provider would be fine.  Bonus points :-) if you can make it selectable independently per node type, as quite certainly you do not want the cluster frontend / NFS server to die suddenly because the spot price has raised above your bid...

**Comment by pvrancx** [comment]
I just sent a PR for my basic spot implementation: see #296 
I've used this to launch clusters with spot compute nodes and non-spot frontend nodes.

**Comment by riccardomurri** [comment]
Many thanks to @pvrancx ! PR #296  has now been merged into the "master" code.  Can anyone give it a try and report on success or issues?

**Comment by nicoulaj** [comment]
It works flawlessly for me :+1: 
I opened a small PR about availability zone placement.

**Comment by nicoulaj** [comment]
A few more feedbacks. Unfortunately, I had to stop using it for several reasons:
 - When requesting a lot of spot instances, it seems that the requests are made ten by ten, with default timeout of ten minutes => it takes 2h for 120 instances
 - When some requests cannot be satisfied, it seems like the hosts registry often gets easily corrupted, resulting in failed deployments/etc.
 - Same when some spot instances get killed while getting configured

After playing with this for a few days, I'm not sure the current conception will ever work perfectly with spot instances: each and every change in the topology requires a full reconfiguration of the whole cluster with Ansible, which can take more than one hour. So if the topology changes during this one hour, breakage can and will happen.

**Comment by riccardomurri** [comment]
I am closing this, as support for spot instances has been available and documented for a while now.

(That ElastiCluster does not handle quick changes to the number of nodes and cannot thus make good use of spot instances, is a known problem -- but matter for another discussion thread.)
