### ISSUE TITLE
problems with selinux handling

### ISSUE THREAD

**Issue by loveshack** [gc3-uzh-ch/elasticluster#600]
The NFS setup fails with an image that doesn't have selinux enabled because setsebool returns an error.  I fixed it as follows (recent master version).  Otherwise, the "temporarily disable selinux" parts look wrong because they need a reboot to take effect.  I assume they should use setenforce iff selinux is enabled.

```
diff --git a/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml b/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml
index 7b43bbe..2098e0a 100644
--- a/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml
+++ b/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml
@@ -17,4 +17,4 @@
 - name: Allow NFS homes through SELinux
   command: |
     setsebool -P use_nfs_home_dirs=1
-  when: 'is_rhel_compatible and fs.mountpoint == "/home"'
+  when: 'is_rhel_compatible and fs.mountpoint == "/home" and ansible_selinux == True'
```

**Comment by riccardomurri** [comment]
>  I assume they should use setenforce iff selinux is enabled.

Done in the latest "master": SELinux-related stuff only runs if Ansible detects SELinux status as "enabled".

> Otherwise, the "temporarily disable selinux" parts look wrong because they need a reboot to take effect.

Last time I checked, it did not harm either :-) except for taking a rather longish time to complete.

There was some discussion on the mailing-list to just disable SELinux at the start of the "common" playbook since no-one seems interested in having it on a batch-queuing cluster...
