### ISSUE TITLE
Jupyterhub login page does not load

### ISSUE THREAD

**Issue by hluetck** [gc3-uzh-ch/elasticluster#601]
Hello,

I am deploying a Jupyterhub server with the latest Elasticluster version. The deployment completes without error, however when trying to load the login page (e.g. https://XYZ.12.345.67/hub/login), the page does not load (Page is not working). The [jupyterhub.log](https://github.com/gc3-uzh-ch/elasticluster/files/2817919/jupyterhub.log) reveals two similar exceptions:
`jinja2.exceptions.TemplateNotFound: login.html`
`jinja2.exceptions.TemplateNotFound: error.html`

I previously deployed this and it worked just fine. What could be the issue?

Thanks for any help.

Best, Henry

**Comment by riccardomurri** [comment]
I recently upgraded Anaconda to the latest version ("2018.12"); since JupyterHub comes from the Anaconda package, it's possible that some changes are needed to the JupyterHub package too.

Up until version 5.3.0 of Anaconda, things worked well.  Can you please try re-creating the cluster with Anaconda 5.3.0 or 5.1.0 and see if that works?  Change your JupyterHub `setup` section by adding a line to set the version of the Anaconda package:

```
[setup/jupyterhub]
global_var_anaconda_version=5.3.0
# ... everything else stays the same
```

**Comment by hluetck** [comment]
It works with Anaconda 5.1.0.

**Comment by riccardomurri** [comment]
I've found the issue: line 52 in `/etc/jupyterhub/jupyterhub_config` currently reads::

    c.JupyterHub.data_files_path = '/opt/anaconda3/share/jupyter/hub'

for Anaconda version `2018.12` (and possibly even `5.3.0`) should read instead::

    c.JupyterHub.data_files_path = '/opt/anaconda3/share/jupyterhub'

(i.e., remove the slash `/` between `jupyter` and `hub`)

I'll commit the change tomorrow, after a clean room test.
