### ISSUE TITLE
no integrity check

### ISSUE THREAD

**Issue by brokenquark** [gc3-uzh-ch/elasticluster#635]
Greetings,

I am a security researcher, who is looking for security smells in Ansible scripts. I found instances where no integrity check is used after downloading an iso or package binaries. According to the Common Weakness Enumeration organization this is a security weakness (Missing Support for Integrity Check: https://cwe.mitre.org/data/definitions/353.html). 

Any feedback is appreciated.

source: https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/roles/jupyter/tasks/pyspark.yml

**Comment by riccardomurri** [comment]
Thanks for taking the time to audit ElastiCluster sources for security
issues!

In this specific case, though, I'm uncertain about what the issue is: you
mention a missing integrity check after download, but there is no download
action in the Ansible file you quoted...

**Comment by brokenquark** [comment]
Hi, 
thanks for your quick response. In line 12 and 26, checksum is not checked. 

We are trying to build an automated tool that can catch these types of cases when no integration check is performed. In your case, local python binary is used without checking. 

Our target is to only detect any coding practice that can lead to exploit or vulnerability. However, in this particular case, it won't lead to any exploit in my humble opinion. 

However, according to CWE, any binary should be gone through an integrity check whenever necessary or unnecessary. We are just trying to build our tools according to that suggestions. 

Thanks again :)

**Comment by riccardomurri** [comment]
> In line 12 and 26, checksum is not checked.

I think there's a misunderstanding about what the actions in that playbook are doing. The `get_checksum: no` lines belong to a `stat:` action, which gathers information about a file on the filesystem of the machine being configured.  In this case, the playbook is only checking whether the files *exist* (in order to decide whether to install the relevant Jupyter kernel description) so there's no need to compute MD5 checksum: we just need to probe if the file is there.

> In your case, local python binary is used without checking.

The local Python binary is supposed to be part of the base OS.  We have to trust something :-)
